import { getNav, buildPage } from "./shared.js";

export function renderMines() {
  var nav = getNav("mines");
  var html = '<div class="head"><div class="logo">MINES</div><div class="tag">PROVABLY FAIR ANALYZER</div></div>';
  html += '<div class="card glow"><h3 class="ct">SMART MINES PREDICTOR</h3><p class="muted">Paste seeds from SportyBet Provably Fair settings. AI calculates safe tiles. NOT fixed code - real math.</p></div>';
  html += '<div class="card"><label>SERVER SEED SHA256 (from Provably Fair)</label><input id="server_seed" placeholder="e.g. bC6NHLluM9ohcJUxo7VYSfJuwyzUcsEbHhactD89"></div>';
  html += '<div class="card"><label>CLIENT SEED (from Provably Fair)</label><input id="client_seed" placeholder="e.g. IV3PnZCfIdjrBxBUgok4-1"></div>';
  html += '<div class="card"><label>NUMBER OF MINES (1-24)</label><input id="num_mines" type="number" min="1" max="24" value="3"></div>';
  html += '<div class="card"><h3 class="ct">5x5 GRID PREVIEW</h3><div id="gridPreview" style="display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:10px"></div><p class="muted" style="margin-top:10px">Click ANALYZE to reveal safe tiles</p></div>';
  html += '<button class="btn" id="goBtn">⚡ ANALYZE MINES ⚡</button>';
  html += '<div id="result"></div>';
  html += "<script>document.getElementById('goBtn').addEventListener('click',async function(){var btn=this;btn.disabled=true;btn.textContent='CALCULATING...';var fd=new FormData();fd.append('server_seed',document.getElementById('server_seed').value);fd.append('client_seed',document.getElementById('client_seed').value);fd.append('num_mines',document.getElementById('num_mines').value);try{var r=await fetch('/api/mines',{method:'POST',body:fd});var d=await r.json();if(d.ok){showResult(d);}else{alert('Error: '+d.error);}}catch(e){alert('Error: '+e.message);}btn.disabled=false;btn.textContent='⚡ ANALYZE MINES ⚡';});function showResult(d){var html='<div class=\"card glow\"><h3 class=\"ct\">RESULT: '+d.confidence+'% CONFIDENCE</h3>';if(d.hash){html+='<p class=\"muted\">SHA512 Hash: '+d.hash+'</p>';}html+='<h3 class=\"ct\" style=\"margin-top:15px\">SAFE TILES (Click These in SportyBet)</h3><div style=\"display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:10px\">';for(var r=0;r<5;r++){for(var c=0;c<5;c++){var cell=d.grid[r][c];var bg=cell.isMine?'#330000':'#003300';var icon=cell.isMine?'✗':'✓';html+='<div style=\"aspect-ratio:1;background:'+bg+';border:2px solid #00ff88;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:18px;color:#00ff88;font-weight:900\">'+icon+'</div>';}}html+='</div></div>';html+='<div class=\"card\"><h3 class=\"ct\">SAFE POSITIONS (Row,Col)</h3><div style=\"display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:10px;text-align:center;font-weight:900;font-size:14px;color:#ffaa00\">';for(var i=0;i<d.minePositions.length;i++){var p=d.minePositions[i];var r=Math.floor(p/5);var c=p%5;html+='<div>['+r+','+c+']</div>';}html+='</div></div>';html+='<button class=\"btn\" onclick=\"location.reload()\">NEW ANALYSIS</button>';document.getElementById('result').innerHTML=html;document.getElementById('result').scrollIntoView({behavior:'smooth'});}</script>";
  return buildPage("MINES", nav, html);
}
