import { getNav, buildPage } from "./shared.js";

export function renderMines() {
  var nav = getNav("mines");
  var html = "<div class=\"head\"><div class=\"logo\">MINES</div><div class=\"tag\">PROVABLY FAIR ANALYZER</div></div>";
  html += "<div class=\"card glow\"><h3 class=\"ct\">SMART MINES PREDICTOR</h3><p class=\"muted\">Paste the server seed and client seed from SportyBet Provably Fair settings. AI calculates safe tiles.</p></div>";
  html += "<div class=\"card\"><label>SERVER SEED SHA256 (from Provably Fair)</label><input id=\"server_seed\" placeholder=\"e.g. ad095eba22b26d20c1b676ada2f789f2a71c766744321df154f35362cb68974b\"></div>";
  html += "<div class=\"card\"><label>CLIENT SEED (from Provably Fair)</label><input id=\"client_seed\" placeholder=\"e.g. oXXQNGGxyKO3euMxwCbm\"></div>";
  html += "<div class=\"card\"><label>NUMBER OF MINES (1-24)</label><input id=\"num_mines\" type=\"number\" min=\"1\" max=\"24\" value=\"3\"></div>";
  html += "<button class=\"btn\" id=\"goBtn\">⚡ ANALYZE MINES ⚡</button>";
  html += "<div id=\"result\"></div>";
  html += "<script>document.getElementById(\"goBtn\").addEventListener(\"click\",async function(){var btn=this;btn.disabled=true;btn.textContent=\"ANALYZING...\";var fd=new FormData();fd.append(\"server_seed\",document.getElementById(\"server_seed\").value);fd.append(\"client_seed\",document.getElementById(\"client_seed\").value);fd.append(\"num_mines\",document.getElementById(\"num_mines\").value);try{var r=await fetch(\"/api/mines\",{method:\"POST\",body:fd});var d=await r.json();if(d.ok){showGrid(d);}else{alert(\"Error: \"+d.error);}}catch(e){alert(\"Error: \"+e.message);}btn.disabled=false;btn.textContent=\"⚡ ANALYZE MINES ⚡\";});function showGrid(d){var html=\"<div class=\\\"head\\\"><div class=\\\"logo\\\">RESULT</div></div>\";html+=\"<div class=\\\"card glow\\\"><h3 class=\\\"ct\\\">CONFIDENCE: \"+d.confidence+\"%</h3></div>\";if(d.aiInsight){html+=\"<div class=\\\"card\\\"><h3 class=\\\"ct\\\">AI INSIGHT</h3><p class=\\\"txt\\\">\"+d.aiInsight+\"</p></div>\";}html+=\"<div class=\\\"card\\\"><h3 class=\\\"ct\\\">SAFE TILES (Click These)</h3><div style=\\\"display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:15px\\\">\";for(var r=0;r<5;r++){for(var c=0;c<5;c++){var cell=d.grid[r][c];var isTop5=d.topPicks.indexOf(cell.pos)!==-1;var bg=cell.isMine?\"#330000\":\"#003300\";var border=isTop5?\"3px solid #ffaa00\":\"1px solid #00ff88\";var label=isTop5?\"★ TOP\":(cell.isMine?\"✗\":\"✓\");html+=\"<div style=\\\"aspect-ratio:1;background:\"+bg+\";border:\"+border+\";border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:20px;color:\"+(isTop5?\"#ffaa00\":\"#00ff88\")+\";font-weight:900\\\">\"+label+\"</div>\";}}html+=\"</div></div>\";html+=\"<div class=\\\"card\\\"><h3 class=\\\"ct\\\">TOP 5 SAFE POSITIONS</h3><div style=\\\"display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:10px;text-align:center;font-size:11px;color:#00ff88\\\"><div>1</div><div>2</div><div>3</div><div>4</div><div>5</div></div><div style=\\\"display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:5px;text-align:center;font-weight:900;font-size:14px;color:#ffaa00\\\">\";for(var i=0;i<5;i++){var p=d.topPicks[i];var r=Math.floor(p/5);var c=p%5;html+=\"<div>[\"+r+\",\"+c+\"]</div>\";}html+=\"</div></div>\";html+=\"<button class=\\\"btn\\\" onclick=\\\"location.reload()\\\">NEW ANALYSIS</button>\";document.getElementById(\"result\").innerHTML=html;document.getElementById(\"result\").scrollIntoView({behavior:\"smooth\"});}</script>";
  return buildPage("MINES", nav, html);
}
